name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    #Build and test service
    - name: Variable Substitution appsettings file for tests
      uses: microsoft/variable-substitution@v1
      with:
        files: 'WebhookReceiver/WebhookReceiver.Tests/appsettings.json'
      env:
        AppSettings.ClientSecret: "${{ secrets.ClientSecret }}"    
    #- name: Build test project
    #  run: dotnet build WebhookReceiver/WebhookReceiver.Tests/WebhookReceiver.Tests.csproj --configuration Release
    - name: Run automated unit and integration tests
      run: dotnet test WebhookReceiver/WebhookReceiver.Tests/WebhookReceiver.Tests.csproj --configuration Release

    #Publish dotnet objects
    - name: DotNET Publish Webhook
      run: dotnet publish WebhookReceiver/WebhookReceiver.Service/WebhookReceiver.Service.csproj --configuration Release
    #Publish build artifacts to GitHub
    - name: Upload web service build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: serviceapp
        path: WebhookReceiver/WebhookReceiver.Service/bin/Release/netcoreapp3.1/publish
    - run: |
         cd WebhookReceiver/WebhookReceiver.Service/bin/Release/netcoreapp3.1/publish
         dir 

  deploy:
    runs-on: windows-latest
    needs: build    

    steps:
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}  
    #Download the artifacts from GitHub
    - name: Download serviceapp artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: serviceapp
    - name: Deploy web service to Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        app-name: samsapp-data-eu-webhook
        package: serviceapp
        slot-name: production
    - run: az webapp config appsettings set --name "samsapp-data-eu-webhook" --resource-group "SamLearnsAzureData" --settings "AppSettings:ClientSecret=${{ secrets.ClientSecret }}"  
